# this is is a list  (almost) all of the tokens in the agendaItemTitles
# unccomment the words toyou want to use in a pattern to filter
# a dataframe
anti_words = c(
  "Accessible Loading Zone",
  "Accessible Parking Space",
  "Accessible Parking Spaces",
  "Address by",
  "All-Way Stop",
  "Announcements",
  "Appeal of Property Standards Order",
  "Appeal Report",
  "Application for Fence Exemption",
  "Application",
  "Appointment of",
  "Appointment to",
  "Appointments to ",
  "Approval",
  "Authority to Issue a Debenture",
  "Award of Doc",
  "Boards of Management",
  "Business Improvement",
  "Call to Order",
  "Chief Executive Officer’s Report",
  "Confirmation of",
  "Confirmation of",
  "Construction Staging Area",
  "Contract Award",
  "Decision Report",
  "Declaration of",
  "Declarations of",
  "Election of",
  "Enactment of By-laws",
  "Encroachment Appeal",
  "Final Report",
  "Fire Routes",
  "Inclusion on the Heritage Register",
  "Introduction of By-laws",
  "Introduction of",
  "Introductions",
  "New Business from City Officials",
  "New Business",
  "Notice of Intention to Designate",
  "Parking Amendment",
  "Parking Amendments",
  "Parking Amendments",
  "Parking Regulation Amendments",
  "Pay-and-Display Parking",
  "Pedestrian Crossing Protection",
  "Petitions",
  "Presentation",
  "Presentations",
  "Procedure",
  "Procurement Authorization",
  "Recess",
  "Renaming",
  "Request for a Fence Exemption",
  "Review of the Order Paper",
  "Road Alteration",
  "Rules of Procedure",
  "Schedule of Meetings",
  "Selection of Candidates",
  "Speed Bumps",
  "Speed Hump Installation",
  "Speed Humps",
  "Speed Limit Reduction",
  "Toronto Parking Authority",
  "Traffic Calming (Speed Humps)",
  "Traffic Calming",
  "Traffic Control Signals",
  "U-Turn",
  "Update",
  "Updates",
  "Zoning By-law Amendment Application",
  "Zoning By-law Amendment"
)
