utils::globalVariables(c("text", "row_id", "data"))

#' @title match key terms
#' @description utility function for categorization using a LUT
#' @param text_vec char
#' @param terms_tbl tibble, Default: key_terms()
#' @return OUTPUT_DESCRIPTION
#' @details this gets called from categorize_txt() or categorize_df()
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @seealso
#'  \code{\link[torontodata:categorize_df]{categorize_txt}}
#'  \code{\link[torontodata:categorize_df]{categorize_df}}
#' @rdname match_key_terms_core
#' @export
#' @importFrom dplyr mutate
#' @importFrom purrr map_dfr
#' @importFrom stringr str_detect str_extract
#' @importFrom tibble tibble
match_key_terms_core <- function(text_vec, terms_tbl = key_terms()) {
  terms_tbl <- terms_tbl |>
    dplyr::mutate(pattern = paste0("\\b", key_terms, "\\b"))

  purrr::map_dfr(
    text_vec,
    function(text) {
      detected <- stringr::str_detect(text, terms_tbl$pattern)
      if (!any(detected)) {
        return(NULL)
      }

      tibble::tibble(
        text = text,
        key_term = terms_tbl$key_terms[detected],
        pattern = terms_tbl$pattern[detected],
        sector = terms_tbl$sectors[detected],
        match = stringr::str_extract(text, terms_tbl$pattern[detected])
      )
    }
  )
}

#' @title categorize text
#' @description using a look up table (LUT), such as one generated by
#' car_terms() or key_terms(), return a datframe with the text, key_term,
#' pattern, sector, match and keyword_count
#' @param text char, a character vector
#' @param terms_tbl a lut as a tibble, Default: key_terms()
#' @return tibble
#' @details DETAILS
#' @examples
#'  txt = "As Green wild fires choke UP with conservation, pedestrians demand
#'  cooling centres. But not climate change."
#'  categorize_txt(txt)
#' @seealso
#'  \code{\link[torontodata:categorize_df]{categorize_df}},
#' @rdname categorize_txt
#' @export
#' @importFrom dplyr add_count arrange desc
categorize_txt <- function(text, terms_tbl = key_terms()) {
  match_tbl <- match_key_terms_core(text, terms_tbl)

  match_tbl |>
    dplyr::add_count(match, name = "keyword_count") |>
    dplyr::arrange(dplyr::desc(.data$keyword_count))
}


#' @title categorize df
#' @description catagorize a dataframe using a named column
#' @param df dataframe
#' @param name_col char, Default: 'agendaItemTitle'
#' @param terms_tbl LUT as a tibble, Default: key_terms()
#' @return tibble
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  example_data <- tibble::tribble(
#'  ~agendaItemTitle, ~id,
#' "Greening the military must align with Climate action", 1,
#' "Deadly nordic heatwave supercharged by climate crisis", 2,
#' "Southwest Airlines sells renewable unit in retreat form climate goals", 3)
#' categorize_df(example_data)
#'  }
#' }
#' @seealso
#'  \code{\link[torontodata:categorize_txt]{categorize_txt}},
#' @rdname categorize_df
#' @export
#' @importFrom dplyr mutate row_number select add_count arrange desc left_join
#' @importFrom rlang sym
#' @importFrom purrr map
#' @importFrom tidyr unnest
#'

categorize_df <- function(
  df,
  name_col = "agendaItemTitle",
  terms_tbl = NULL
) {
  if (is.null(terms_tbl)) {
    terms_tbl <- key_terms()
  }
  if (!name_col %in% names(df)) {
    stop("The specified name column does not exist in the dataframe.")
  }

  df <- df |>
    dplyr::mutate(row_id = dplyr::row_number())

  match_tbl <- df |>
    dplyr::select(.data$row_id, !!rlang::sym(name_col)) |>
    dplyr::mutate(
      matches = purrr::map(
        !!rlang::sym(name_col),
        ~ match_key_terms_core(.x, terms_tbl)
      )
    ) |>
    dplyr::select(-!!rlang::sym(name_col)) |>
    # check for new interface
    tidyr::unnest(, c(.data$matches), keep_empty = TRUE) |>
    dplyr::select(-text)

  # Add global keyword count
  match_tbl <- match_tbl |>
    dplyr::add_count(.data$match, name = "keyword_count") |>
    dplyr::arrange(dplyr::desc(.data$keyword_count))

  dplyr::left_join(df, match_tbl, by = "row_id") |>
    dplyr::select(-row_id)
}
