#' @title data decision body title
#' @description returns a tibble with the decisionBodyId, decisionBodyCode and decisionBodyName for the Toronto Council commitees

#' @return tibble
#' @details decisionBodyCode is not something that exists in the API, but
#' something I made up that is the first two (or three!, careful) LETTERS
#' of the referenceNumber of an agenda item
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @seealso
#'  \code{\link[tibble]{tribble}}
#' @rdname lut_decisionbody_id_code_name
#' @export
#' @importFrom tibble tribble
lut_decisionbody_id_code_name <- function() {
  # per https://secure.toronto.ca/council/#/committees
  # last update 2025-08-08 15:49:59 EDT
  tibble::tribble(
    ~decisionBodyId,
    ~decisionBodyCode,
    ~decisionBodyName,
    # Toronto City Council
    2462L,
    "CC",
    "City Council",
    2462L,
    "DM",
    "Other Deferred Matters",
    2462L,
    "RM",
    "Routine Matters",
    2462L,
    "IA",
    "Administrative Inquiry",
    2462L,
    "MM",
    "Member Motions",
    2462L,
    "BL",
    "Bills and By-Laws",

    # Committees Reporting to City Council
    2582L,
    "AU",
    "Audit Committee",
    2564L,
    "HL",
    "Board of Health",
    2562L,
    "BU",
    "Budget Committee",
    2583L,
    "CA",
    "Civic Appointments Committee",
    2585L,
    "NC",
    "Corporations Nominating Panel",
    2563L,
    "EC",
    "Economic and Community Development Committee",
    2468L,
    "EX",
    "Executive Committee",
    2542L,
    "GG",
    "General Government Committee",
    2566L,
    "IE",
    "Infrastructure and Environment Committee",
    2565L,
    "PH",
    "Planning and Housing Committee",
    2463L,
    "ST",
    "Striking Committee",
    # Community Councils
    2464L,
    "EY",
    "Etobicoke York Community Council",
    2465L,
    "NY",
    "North York Community Council",
    2467L,
    "SC",
    "Scarborough Community Council",
    2466L,
    "TE",
    "Toronto and East York Community Council",
    # Other Boards and Committees
    2749L,
    "AA",
    "Aboriginal Affairs Advisory Committee",
    2469L,
    "BA",
    "Bid Award Panel",
    2724L,
    "HU",
    "Board of Health - Budget Committee",
    2725L,
    "HP",
    "Board of Health - Performance Appraisal of the Medical Officer of Health",
    2864L,
    "HX",
    "Board of Health - Strategic Plan Development Committee",
    2644L,
    "BV",
    "Budget Subcommittee at City Hall",
    2647L,
    "BZ",
    "Budget Subcommittee at Etobicoke Civic Centre",
    2645L,
    "BW",
    "Budget Subcommittee at North York Civic Centre",
    2646L,
    "BX",
    "Budget Subcommittee at Scarborough Civic Centre",
    2765L,
    "TS",
    "City-School Boards Advisory Committee",
    2704L,
    "EA",
    "Compliance Audit Committee",
    2744L,
    "CR",
    "Confronting Anti-Black Racism Advisory Committee",
    2483L,
    "RA",
    "CreateTO",
    2512L,
    NA_character_,
    "CreateTO - Human Resources Committee",
    2642L,
    "DG",
    "Dangerous Dog Review Tribunal",
    2602L,
    "DB",
    "Debenture Committee",
    2510L,
    "EP",
    "Exhibition Place",
    2904L,
    "FW",
    "FIFA World Cup 2026 Subcommittee",
    2745L,
    "FB",
    "Film, Television and Digital Media Advisory Board",
    2750L,
    "HS",
    "Housing Rights Advisory Committee",
    2924L,
    "LR",
    "Labour Relations Subcommittee",
    2844L,
    "LC",
    "Long-Term Care Committee of Management",
    2588L,
    "AF",
    "Members of the Toronto Atmospheric Fund",
    2627L,
    "NM",
    "Nominating Panel - Administrative Penalty Tribunal",
    2622L,
    "NA",
    "Nominating Panel - Committee of Adjustment",
    2623L,
    NA_character_,
    "Nominating Panel - Compliance Audit Committee",
    2628L,
    "ND",
    "Nominating Panel - Dangerous Dog Review Tribunal",
    2804L,
    "NH",
    "Nominating Panel - Multi-Tenant House Licensing Tribunal",
    2624L,
    "NP",
    "Nominating Panel - Property Standards Committee",
    2629L,
    NA_character_,
    "Nominating Panel - Rooming House Licensing Commissioner and Deputy Commissioner",
    2630L,
    "NS",
    "Nominating Panel - Sign Variance Committee",
    2625L,
    "NL",
    "Nominating Panel - Toronto Licensing Tribunal",
    2626L,
    "XV",
    "Nominating Panel - Toronto Local Appeal Body",
    2505L,
    "SV",
    "Property Standards - Etobicoke York Panel",
    2509L,
    "SY",
    "Property Standards - North York Panel",
    2484L,
    "SX",
    "Property Standards - Scarborough Panel",
    2502L,
    "SZ",
    "Property Standards - Toronto and East York Panel",
    2703L,
    "PS",
    "Property Standards Committee",
    2784L,
    "SE",
    "Service Excellence Committee",
    2643L,
    "SB",
    "Sign Variance Committee",
    2683L,
    "TM",
    "Subcommittee on Metrolinx's Ontario Line Construction",
    2482L,
    "CT",
    "TO Live",
    2503L,
    "RG",
    "TO Live - Environmental, Social and Governance Committee",
    2522L,
    "RZ",
    "TO Live - Finance and Audit Committee",
    2488L,
    "RY",
    "TO Live - Human Resources and Stakeholder Relations Committee",
    2586L,
    "DI",
    "Toronto Accessibility Advisory Committee",
    2587L,
    "TA",
    "Toronto Atmospheric Fund",
    2748L,
    "FA",
    "Toronto Francophone Affairs Advisory Committee",
    2491L,
    "IB",
    "Toronto Investment Board",
    2746L,
    "MA",
    "Toronto Music Advisory Committee",
    2490L,
    "PA",
    "Toronto Parking Authority",
    2663L,
    "PR",
    "Toronto Parking Authority - Audit and Risk Management Committee",
    2511L,
    "PB",
    "Toronto Preservation Board",
    2944L,
    "TTC",
    "Toronto Transit Commission",
    2964L,
    "TTA",
    "Toronto Transit Commission - Audit & Risk Management Committee",
    2945,
    "TTH",
    "Toronto Transit Commission - Human Resources Committee",
    2984L,
    "TTS",
    "Toronto Transit Commission - Strategic Planning Committee",
    2489L,
    "ZB",
    "Toronto Zoo",
    2631L,
    "NZ",
    "Tribunals Nominating Panel",
    2747L,
    "QS",
    "Two-Spirit, Lesbian, Gay, Bisexual, Transgender and Queer Advisory Committee"
  )
}
